server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: Orderservice
  cloud:
    nacos:
#      server-addr: http://169.254.155.219:8848
      server-addr: http://192.168.42.233:8845
      discovery:
        cluster-name: HZ
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

feign:
  httpclient:
    client:
    enabled: true
    connection-timeout: 20000
    max-connections: 200 #最大连接数
    max-connections-per-route: 50
